### ISSUE TITLE
404 error for Debian repo because of a typo

### ISSUE THREAD

**Issue by slym** [stackhpc/ansible-role-beegfs#36]
Default URL for Debian repo is not correct because of an underscore instead of a dash :
 
Bad one : https://www.beegfs.io/release/latest-stable/dists/beegfs_deb9.list
Good one : https://www.beegfs.io/release/latest-stable/dists/beegfs-deb9.list

I replaced it in my setup in stackhpc.beegfs/defaults/main.yml and it worked.

Weird thing is that for RHEL 7 only IT IS an underscore and not a dash ... (check file listing @ https://www.beegfs.io/release/beegfs_7_1/dists/ and see for yourself) :-)

**Comment by brtknr** [comment]
Cool, thanks for finding a fix. Would you like to send a pull request?

**Comment by slym** [comment]
No thanks. I prefer to let you patch it.
Another little thing : you could add "apt-transport-https" as prerequisite to be able to download from the repo. It does not seem to be installed by default even on recent Debian versions.
