### ISSUE TITLE
Add "apt-transport-https" as prerequisite in Debian

### ISSUE THREAD

**Issue by brtknr** [stackhpc/ansible-role-beegfs#38]
You could add "apt-transport-https" as prerequisite to be able to download from the repo. It does not seem to be installed by default even on recent Debian versions.

_Originally posted by @slym in https://github.com/stackhpc/ansible-role-beegfs/issues/36#issuecomment-458457900_

**Comment by brtknr** [comment]
I created a separate issue as this is unrelated to the #36.

Is it possible that you are using a trimmed down version of Debian @slym? I will leave this issue here for now so that other users can reference it.

**Comment by slym** [comment]
I'm using default install with GUI (xFCE) from debian-9.5.0-amd64-xfce-CD-1.iso.
In all cases, the ansible paybook should check for its presence before adding an HTTPS repo.
Thank you for your time.
