### ISSUE TITLE
OS tuning should be controllable and configurable

### ISSUE THREAD

**Issue by oneswig** [stackhpc/ansible-role-beegfs#8]
We might not always want to apply the recommended tuning parameters for BeeGFS.  A global enable flag (defaulting to enabled?) should be introduced.

**Comment by brtknr** [comment]
Would it be acceptable to force an empty list which yields no tuning?

**Comment by oneswig** [comment]
Not all the tuning is based on specific devices.  The sysctl parameters for example.  It's plausible that a user might want to apply the global parameters but none of the device-specific ones.  So I think a global enable flag still has purpose.  It could easily be applied at the inclusion of the tuning yml file.
